name: Build & Publish NPM Package

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      version:
        description: "Version to publish"
        required: true
        type: string
        # Default to truncated commit hash
        default: "0.0.0"
      tag:
        description: "Tag to publish"
        required: true
        type: string
        default: "latest"

permissions:
  contents: read
  # For provenance generation
  id-token: write

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    environment: NPM Deploy
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v2

      - uses: actions/setup-node@v4
        with:
          node-version: "22"
          registry-url: "https://registry.npmjs.org"

      # Code is not minified and bundled anymore
      #- name: Build
      #  run: bun run build

      - name: Change version in package.json to ${{ github.event.inputs.version }}, defaulting to the truncated commit hash
        run: 'sed -i ''s/"version": ".*"/"version": "${{ github.event.inputs.version }}"/'' package.json'

      - name: Publish to NPM
        run: npm publish --provenance --tag ${{ github.event.inputs.tag }} --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
