name: "Publish documentation"
on:
  push:
    branches:
      - "main"

jobs:
  publish-documentation:
    permissions:
      id-token: "write"
      pages: "write"

    environment:
      name: "github-pages"
      url: "${{ steps.deployment.outputs.page_url }}"

    runs-on: "ubuntu-latest"
    steps:
      - id: "checkout"
        name: "Check out Git repository"
        uses: "actions/checkout@v3"

      - id: "setup-bun"
        name: Setup Bun
        uses: "oven-sh/setup-bun@v2"

      - id: "install-dependencies"
        name: "Install Node.js dependencies"
        run: |
          set -euo pipefail
          bun add typedoc --frozen-lockfile 
      - id: "build"
        name: "Build documentation"
        run: |
          set -euo pipefail
          bunx typedoc --customFooterHtml "Made with Love and 🍵 by <strong><a href="https://kitsu.life/">Kitsu</a></strong>!"
      - id: "upload-documentation"
        name: "Upload Pages artifact"
        uses: "actions/upload-pages-artifact@v2"
        with:
          path: "docs/"

      - id: "deployment"
        name: "Deploy documentation to GitHub Pages"
        uses: "actions/deploy-pages@v2"
